### ISSUE TITLE
[Windows]: Multiple net adapters produce an error while installing

### ISSUE THREAD

**Issue by stavros-k** [cloudradar-monitoring/rport-pairing#6]
Having more than 1 network adapter, where the only 1 is connected, produces the following error.

While it does not stop the execution of the script, might be a good idea to handle that scenario.
Without being 100% sure, I think disconnected adapters get an APIPA IP address (169.254.0.0 - 169.254.255.255)

```
PS C:\windows\system32> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS C:\windows\system32> $url="https://pairing.rport.io/2zfb7bc"
PS C:\windows\system32> Invoke-WebRequest -Uri $url -OutFile "rport-installer.ps1"
PS C:\windows\system32> powershell -ExecutionPolicy Bypass -File .\rport-installer.ps1 -x -i
* Testing connection to http://rport.localdomain:80 has succeeded.
* Downloading  https://downloads.rport.io/rport/stable/latest.php?arch=Windows_x86_64 .
* Download finished and stored to C:\Windows\temp\rport_stable_Windows_x86_64.zip .
* RPort Client version 0.7.0 installed.
* Creating new configuration file C:\Program Files\rport\rport.conf.
* Looking for script interpreters.
* 0 script interpreters found.
* Monitoring for net_lan 'Ethernet 2' already activated. Skipping.
Cannot convert argument "d", with value: "0 bps", for "Floor" to type "System.Double": "Cannot convert value "0 bps"
to type "System.Double". Error: "Input string was not in a correct format.""
At C:\windows\system32\rport-installer.ps1:253 char:5
+     $linkSpeed = [math]::floor($linkSpeed);
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

* Monitoring for net_wan 'Ethernet' already activated. Skipping.

* Registering rport as a windows service.
Service installed

Status   Name               DisplayName
------   ----               -----------
Running  rport              Rport Client
* Tacoscript already installed to C:\Program Files\tacoscript\bin\tacoscript.exe
* No Tacoscript update needed. You are on the latest 0.2.0 version.

* Uninstaller created in C:\Program Files\rport\uninstall.bat.
#
#
#  Installation of rport finished.
#
#  This client is now connected to http://rport.localdomain:80
#
#  Look at C:\Program Files\rport\rport.conf and explore all options.
#  Logs are written to C:\Program Files\rport/rport.log.
#
#  READ THE DOCS ON https://kb.rport.io/
#
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#  Give us a star on https://github.com/cloudradar-monitoring/rport
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
#

Thanks for using
  _____  _____           _
 |  __ \|  __ \         | |
 | |__) | |__) |__  _ __| |_
 |  _  /|  ___/ _ \| '__| __|
 | | \ \| |  | (_) | |  | |_
 |_|  \_\_|   \___/|_|   \__|

```

**Comment by prjus** [comment]
Upgrading RPort on one of our clients results in an error:

`Set-TomlVar : Key net_wan not found in config content
At C:\Windows\TEMP\rport-update.ps1:393 char:22
+ ... igContent = Set-TomlVar -ConfigContent $ConfigContent -Block "monitor ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-TomlVar`

Output from Get-Netadapter:

`Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet                  Realtek PCIe GbE Family Controller           14 Disconnected D4-5D-64-1E-6F-C7          0 bps
Ethernet 2                Lenovo Giga Ethernet                         11 Up           E0-4F-43-93-6D-BC         1 Gbps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             18 Up           00-15-5D-13-B8-5F        10 Gbps
`

Perhaps the old error that I have reported before (the '0 bps')?

**Comment by thorstenkramm** [comment]
@prjus 
No. This issue is more or less planned. 
You are upgrading from some old 0.5.X versions, that doesn't support network monitoring.

Before executing the update, open `rport.conf` and on the `[monitoring]` block, and insert these lines
```
  ## Monitor the bandwidth usage of the following maximum two network cards:
  ## 'net_lan' and 'net_wan'.
  ## You must specify the device name and the maximum speed in Megabits.
  ## On Windows use 'Get-Netadapter' to discover adapter names.
  ## Examples:
  ## net_lan = [ 'eth0' , '1000' ]
  ## net_wan = ['Ethernet0', '1000']
  #net_lan = ['', '1000']
  #net_wan = ['', '1000']
```
Then execute the update again. 
Now the key `net_wan` will be found and set properly. 

I admit, the script should be able to extend the config automatically.

**Comment by prjus** [comment]
There is also this error:

```
Get-NetAdapter : No MSFT_NetAdapter objects found with property 'Name' equal to 'XXXX'.  Verify the value of the proper
ty and retry.
At C:\windows\TEMP\rport-update.ps1:410 char:27
+ ... if ("Up" -eq (Get-NetAdapter -Name $NetAdapter.InterfaceAlias).Status ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (XXXX:String) [Get-NetAdapter], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Get-NetAdapter
 ```
 
 I would like to suggest for instance a try/catch around the following code around line 410:

``` 
             if ("Up" -eq (Get-NetAdapter -Name $NetAdapter.InterfaceAlias).Status)
            {
                $filtered += $NetAdapter
            }
```

**Comment by thorstenkramm** [comment]
@prjus 
What's the output of `Get-NetAdapter` on your system?

**Comment by thorstenkramm** [comment]
@prjus And what does `Get-NetIPAddress|select InterfaceAlias` give you?

**Comment by prjus** [comment]
```
InterfaceAlias               
--------------               
Ethernet 5                   
Ethernet 4                   
Ethernet 6                   
vEthernet (C2IT)             
vEthernet (Wi-Fi)            
vEthernet (Ethernet 4)       
vEthernet (Ethernet 6)       
vEthernet (Default Switch)   
vEthernet (Ethernet 5)       
vEthernet (nat)              
LAN-forbindelse* 2           
Bluetooth-netværksforbindelse
LAN-forbindelse* 1           
Wi-Fi                        
Loopback Pseudo-Interface 1  
Ethernet 5                   
Ethernet 4                   
Ethernet 6                   
vEthernet (C2IT)             
vEthernet (Wi-Fi)            
vEthernet (Ethernet 4)       
vEthernet (Ethernet 6)       
vEthernet (Default Switch)   
vEthernet (Ethernet 5)       
vEthernet (nat)              
LAN-forbindelse* 2           
Bluetooth-netværksforbindelse
LAN-forbindelse* 1           
Wi-Fi                        
Loopback Pseudo-Interface 1  
C2IT                         
```

**Comment by prjus** [comment]
The problem with the code i guess is that "Status" is "Not Present" for two of the results from Get-Netadapter, which I think the try/catch will at least circumvent and stop the script from failing to do the update.

**Comment by thorstenkramm** [comment]
@prjus So I assume ` No MSFT_NetAdapter objects found with property 'Name' equal to 'XXXX'.`  was not the real error. Did you put XXX for privacy? 
So, which one has caused the error. Try/catch is good. I'll implement this soon. But if some items can be cleanly filtered out by another criteria, it's even better.

**Comment by prjus** [comment]
> @prjus So I assume ` No MSFT_NetAdapter objects found with property 'Name' equal to 'XXXX'.` was not the real error. Did you put XXX for privacy? So, which one has caused the error. Try/catch is good. I'll implement this soon. But if some items can be cleanly filtered out by another criteria, it's even better.

Probably the last "C2IT" which is a VPN that uses Windows' built-in VPN but with a 3rd party provider Pulse Secure found in Microsoft Store.

**Comment by prjus** [comment]
Yes 😊


Med venlig hilsen / Best regards,

Preben Justesen
+45 25 55 59 95<tel:+45%2025%2055%2059%2095>
***@***.******@***.***>
***@***.***<https://c2it.dk/>

HELPDESK: +45 72 16 17 11 | ***@***.******@***.***>
